config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/show'
  get 'home/index'
  post 'home/index'
  post 'home/show'
  root 'home#index'
  resources :show
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crypto_controller.rb
class CryptoController < ApplicationController

#  "https://coinmarketcap.com/all/views/all"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
      def index
        StartScrap.new.save
        @cryptos = Crypto.all
        @crypto = Crypto.new
      end
    def show 
      @crypto = Crypto.find_by(name: params[:home][:name])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crypto_helper.rb
module CryptoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
 <div class = "text-center">
 <div id ="k">
 <div class="row">
   <div class="col-md-6 col-md-offset-3">
     <%= form_for(:home, url: home_show_path) do |f| %>
         <%= f.label :cryptomonnaie %>
       <%= f.text_field :name, class: 'form-control' %>
       <div >
       <p id="z"><%=f.submit "search", class: "btn btn-primary" %></p>
   
     <% end %>
     </div>
   </div>
 </div>
 </div>
 </div>

app/views/home/show.html.erb
<div class = "text-center">
<div id = "q">
        <% if @crypto && @crypto.name && @crypto.value %>
                La valeur d'un <%= @crypto.name %> est : <%= @crypto.value %>
        <% else %>
                demande en une autre thxdemande une Crypto qui existe stp
        <%end%><br><br><br>
        <a href = "<%=home_index_path%>">
        clique ici pour faire une nouvelle recherche
        </a>
</div>
</div>

app/views/layouts/_header.html.erb
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<nav class="navbar navbar-dark bg-dark">
                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="navbar-collapse collapse" id="navbarNavAltMarkup" style="">
            <div class="navbar-nav">
                <h2><a class="text-white" href="<%=home_index_path%>">Accueil </a> </h2>
                <h2><a class="text-white" href="<%=home_show_path%>">Inscription </a> </h2>
                <a class="nav-link" href="#">Connexion</a>   
            </div>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= yield %>
  </body>
</html>